/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yyqian_OCR */

#ifndef _Included_com_yyqian_OCR
#define _Included_com_yyqian_OCR
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yyqian_OCR
 * Method:    parse
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yyqian_OCR_parse
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_yyqian_OCR
 * Method:    parseStatic
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yyqian_OCR_parseStatic
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
